apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nwya
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0049-tenant/tkrw-pr712-0075-0049-app/devfile-sample-nwya@sha256:e04cae5e953675c11c41ed34f0fcd2f4eaf929bced1764d503b9c4eca765abc9
        name: my-nodejs
        resources: {}
status: {}
